const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

exports.generatePDFSummary = async (summary, id)=>{
    return new Promise((resolve, reject)=>{
        try{
            const dir = path.join(__dirname, '..', '..', 'reports');
            if(!fs.existsSync(dir)) fs.mkdirSync(dir, {recursive:true});
            const filePath = path.join(dir, `report_${id}.pdf`);
            const doc = new PDFDocument({size:'A4', margin:50});
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);
            doc.fontSize(20).text(summary.title, {align:'center'});
            doc.moveDown();
            doc.fontSize(12).text('Highlights:');
            summary.highlights.forEach(h => doc.text('- ' + h));
            doc.moveDown();
            doc.fontSize(12).text('Raw data (JSON):');
            doc.fontSize(8).text(JSON.stringify(summary.raw, null, 2), {width:500});
            doc.addPage();
            doc.fontSize(10).text('Generated by PharmaIntel AI Portal', {align:'center'});
            doc.end();
            stream.on('finish', ()=> resolve('/reports/report_' + id + '.pdf'));
        }catch(e){
            reject(e);
        }
    });
};
